Currently disable Jetbrains code inspect

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -51,30 +51,30 @@ jobs:
     - name: Dotnet code style
       run: dotnet build -c Debug -p:EnforceCodeStyleInBuild=true
 
-    - name: Restore Tools
-      run: |
-        dotnet tool restore
-        dotnet tool install --global nvika 
-        dotnet tool install --global JetBrains.ReSharper.GlobalTools
+    # - name: Restore Tools
+    #   run: |
+    #     dotnet tool restore
+    #     dotnet tool install --global nvika 
+    #     dotnet tool install --global JetBrains.ReSharper.GlobalTools
 
-    - name: CodeFileSanity
-      run: |
-        # TODO: Add ignore filters and GitHub Workflow Command Reporting in CFS. That way we don't have to do this workaround.
-        # FIXME: Suppress warnings from templates project
-        exit_code=0
-        while read -r line; do
-          if [[ ! -z "$line" ]]; then
-            echo "::error::$line"
-            exit_code=1
-          fi
-        done <<< $(dotnet codefilesanity)
-        exit $exit_code
+    # - name: CodeFileSanity
+    #   run: |
+    #     # TODO: Add ignore filters and GitHub Workflow Command Reporting in CFS. That way we don't have to do this workaround.
+    #     # FIXME: Suppress warnings from templates project
+    #     exit_code=0
+    #     while read -r line; do
+    #       if [[ ! -z "$line" ]]; then
+    #         echo "::error::$line"
+    #         exit_code=1
+    #       fi
+    #     done <<< $(dotnet codefilesanity)
+    #     exit $exit_code
 
-    - name: InspectCode
-      run: jb inspectcode $(pwd)/Danmaku!.sln --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN
+    # - name: InspectCode
+    #   run: jb inspectcode $(pwd)/Danmaku!.sln --no-build --output="inspectcodereport.xml" --caches-home="inspectcode" --verbosity=WARN
 
-    - name: NVika
-      run: nvika parsereport "${{github.workspace}}/inspectcodereport.xml" --treatwarningsaserrors
+    # - name: NVika
+    #   run: nvika parsereport "${{github.workspace}}/inspectcodereport.xml" --treatwarningsaserrors
 
   auto-format:
     runs-on: ubuntu-latest
